---
- hosts: chronam-servers
  vars:
    CHRONAM_HOME: "/opt/chronam"
    SOLR_VERSION: 4.10.4
    SOLR_HOME: "/opt/solr"
  tasks:
  - name: create {{SOLR_HOME}}
    file: path={{SOLR_HOME}} mode=0775 state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}}
    become: yes

  - name: download solr {{SOLR_VERSION}}
    get_url: dest=/tmp/solr-{{SOLR_VERSION}}.tgz url=http://archive.apache.org/dist/lucene/solr/{{SOLR_VERSION}}/solr-{{SOLR_VERSION}}.tgz

  - name: untar solr {{SOLR_VERSION}}
    unarchive: src=/tmp/solr-{{SOLR_VERSION}}.tgz dest=/tmp creates=/tmp/solr-{{SOLR_VERSION}}

  - name: copy example directory to {{SOLR_HOME}}
    synchronize: dest={{SOLR_HOME}} src=/tmp/solr-{{SOLR_VERSION}}/example/ recursive=yes
    delegate_to: "{{inventory_hostname}}"

  - name: create solr user
    user: name=solr home={{SOLR_HOME}} shell=/bin/bash
    become: yes

  - name: change {{SOLR_HOME}} owner and group to solr
    file: path={{SOLR_HOME}} owner=solr group=solr mode=0775 state=directory recurse=yes
    become: yes

  - name: Copy chronam config files
    copy: dest={{item.dest}} src={{item.src}} 
    with_items:
      - { src: 'conf/jetty7.sh', dest: '/etc/init.d/jetty.service' }
      - { src: 'conf/schema.xml', dest: "{{SOLR_HOME}}/solr/collection1/conf/schema.xml" }
      - { src: 'conf/solrconfig.xml', dest: "{{SOLR_HOME}}/solr/collection1/conf/solrconfig.xml" }
      - { src: 'conf/jetty-ubuntu', dest: '/etc/default/jetty' }
    become: yes

  - name: Make jetty script executable
    file: path=/etc/init.d/jetty.service mode=0775
    become: yes

  - name: start solr
    service: name=jetty state=started
    become: yes
