---
- hosts: chronam-servers
  vars:
    SOLR_VERSION: 4.10.4
    SOLR_HOME: "/usr/share/jetty8"
  tasks:
#assumes that jetty8 has already been installed at this point
  - name: download solr {{SOLR_VERSION}}
    get_url: dest=/tmp/solr-{{SOLR_VERSION}}.tgz url=http://archive.apache.org/dist/lucene/solr/{{SOLR_VERSION}}/solr-{{SOLR_VERSION}}.tgz

  - name: untar solr {{SOLR_VERSION}}
    unarchive: src=/tmp/solr-{{SOLR_VERSION}}.tgz dest=/tmp creates=/tmp/solr-{{SOLR_VERSION}}

  - name: copy example directory to {{SOLR_HOME}}
    synchronize: dest={{SOLR_HOME}} src=/tmp/solr-{{SOLR_VERSION}}/example/ recursive=yes rsync_opts=--ignore-existing
    delegate_to: "{{inventory_hostname}}"
    become: yes

  - name: Copy chronam config files
    copy: dest={{item.dest}} src={{item.src}} 
    with_items:
      - { src: 'conf/schema.xml', dest: "{{SOLR_HOME}}/solr/collection1/conf/schema.xml" }
      - { src: 'conf/solrconfig.xml', dest: "{{SOLR_HOME}}/solr/collection1/conf/solrconfig.xml" }
    become: yes

  - name: start solr
    service: name=jetty8 state=started
    become: yes
